
name: Deploy Rasa X
on:
  push:
    branches:
    - 'master'
    - 'k8s' # for testing only
    # TODO: other conditions for deployment

env:
  GCLOUD_ZONE_ID: ${{ secrets.GCLOUD_ZONE_ID }}
  GCLOUD_CLUSTER_NAME: ${{ secrets.GCLOUD_CLUSTER_NAME }}
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  RASA_X_IMAGE_NAME: ${{ secrets.RASA_X_IMAGE_NAME }}
  ACTION_SERVER_IMAGE_NAME: ${{ secrets.ACTION_SERVER_IMAGE_NAME }}
  RASA_X_DOMAIN: ${{ secrets.RASA_X_DOMAIN }}
  SARA_GKE_SERVICE_ACCOUNT_NAME: ${{ secrets.SARA_GKE_SERVICE_ACCOUNT_NAME }}
  RASA_X_USERNAME: ${{ secrets.RASA_X_USERNAME }}
  RASA_X_DATABASE_PASSWORD: ${{ secrets.RASA_X_DATABASE_PASSWORD }}
  RASA_X_PASSWORD: ${{ secrets.RASA_X_PASSWORD }}
  RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  RASA_TOKEN: ${{ secrets.RASA_TOKEN }}
  RASA_X_TOKEN: ${{ secrets.RASA_X_TOKEN }}
  JWTSECRET: ${{ secrets.JWTSECRET }}
  PASSWORDSALT: ${{ secrets.PASSWORDSALT }}

  STATIC_IP: "sara-ip"
  INGRESS_CERTIFICATE: "sara-certificate"
  NAMESPACE: "sara"
  RELEASE_NAME: "rasa-x"
  ACTION_SERVER_TAG: "566"
  RASA_X_VERSION: "0.35.0"
  RASA_VERSION: "2.2.8"

  # Due to the issue with openssl library for Google Cloud SDK (gcloud)
  # (https://github.com/GoogleCloudPlatform/github-actions/issues/128)
  # we use 297.0.01 version
  GCLOUD_VERSION: "297.0.1"



jobs:
  deploy_to_k8s_cluster:
    name: Rasa Enterprise K8s deployment
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v2

    - name: Install Helm and helmfile ⛑
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

        sudo curl -fsSL https://github.com/roboll/helmfile/releases/download/v0.130.0/helmfile_linux_amd64 --output /usr/local/bin/helmfile
        sudo chmod +x /usr/local/bin/helmfile

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@e23988b2af9696c66e87d1efbc688d3a80c3be14
      name: Authenticate with gcloud 🎫
      with:
        version: "${{ env.GCLOUD_VERSION }}"
        service_account_email: ${{ env.SARA_GKE_SERVICE_ACCOUNT_NAME }}
        service_account_key: ${{ secrets.SARA_GKE_SERVICE_ACCOUNT_KEY }}

    - name: Authenticate docker and configure cluster credentials 🎫
      run: |
        # Set up docker to authenticate via gcloud command-line tool.
        gcloud  --quiet auth configure-docker
        gcloud container clusters get-credentials "$GCLOUD_CLUSTER_NAME" --project ${GCLOUD_PROJECT_ID} --zone "$GCLOUD_ZONE_ID"

    - name: Prepare namespace
      run: |
        kubectl config set-context --current --namespace="${NAMESPACE}"

    - name: Deploy Rasa X chart ☸️
      run: |
        cd ${{ github.workspace }}/.github/deployments && 
        helmfile repos &&
        helmfile --environment development sync

    - name: Wait for deployment to be ready ⏰
      run: |
        kubectl wait \
          --for=condition=available \
          --timeout=600s \
          -l "app.kubernetes.io/component=rasa-x" deployment

        # Wait for DB migration to be done
        until [[ $(curl -s "https://${{ env.RASA_X_DOMAIN }}/api/health" | tee /tmp/output_status.txt | jq -r .database_migration.status) -eq "completed" ]]
        do
          cat /tmp/output_status.txt || true
          sleep 5
        done
